const maths=require("./maths")
console.log("sum :",maths.sum(2,2))
console.log("subtract :",maths.subtract(2,2))
console.log("multiply :",maths.multiply(2,2))
console.log("division :",maths.division(2,2))
